[mongo]
uri = "mongodb+srv://ruchirsarve11:11HhijRWrB3lJVYfEr@streamlitfree.cblfh.mongodb.net/?retryWrites=true&w=majority&appName=streamlitfree"

[GOOGLE_API_KEY]
value = "AIzaSyA6RJDRYZaprJ7-3kbT-0qWbCllajjfCYI111"